### ISSUE TITLE
1.12.2 not working

### ISSUE THREAD

**Issue by Cardboard-Friend** [ronappleton/multicraft-confs#1]
I followed all the instructions but it is still not working.
logs:
23.11 17:15:46 [Multicraft] Starting server!
23.11 17:15:46 [Multicraft] Loaded config for "Mod: Forge 1.12.2"
23.11 17:15:46 [Multicraft] Updating eula.txt file
23.11 17:15:47 [Server] INFO A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
23.11 17:15:47 [Server] INFO at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23.11 17:15:47 [Server] INFO at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
23.11 17:15:47 [Server] INFO at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23.11 17:15:47 [Server] INFO at java.base/java.lang.reflect.Method.invoke(Method.java:567)
23.11 17:15:47 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
23.11 17:15:47 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
23.11 17:15:47 [Server] INFO Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
23.11 17:15:47 [Server] INFO at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
23.11 17:15:47 [Server] INFO at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
23.11 17:15:47 [Server] INFO ... 6 more
23.11 17:15:47 [Multicraft] Server shut down (starting)
23.11 17:15:47 [Multicraft] Restarting crashed server in 5.0 seconds
23.11 17:15:47 [Multicraft] Stopping server!
23.11 17:15:49 [Multicraft] Looks like a crash, check the server console. Return value: 1
23.11 17:15:49 [Multicraft] Server stopped

**Comment by ronappleton** [comment]
Hi @Cardboard-Friend sorry its taken a year to spot this, I don't look in here often, it was really created for servers I create with my daughter.

If you still need help, then I am willing, if you can describe your actions a bit better I can probably help a little more.
